Repository LArSoft/larg4, pull requests merged in 2020-02, with the labels that each got.

#2 auxdet that merges steps by particle, change verbosity of the analys…
  larg4/Analysis/CheckAuxDetHit_module.cc
  larg4/Analysis/CheckMCParticle_module.cc
  larg4/Services/AuxDetSD.cc
  larg4/Services/AuxDetSD.h
  larg4/Services/LArG4Detector_service.cc
  larg4/Services/TempHit.h
Labels: L1-approved, L2-approved, code-checks-approved, fully-signed, tests-approved

#4 Add two github actions to move new pull requests or issues to the LArSoft pull request project
  .github/workflows/opened-issues-triage.yml
  .github/workflows/opened-pulls-triage.yml
Labels: L1-approved, code-checks-approved, new-package-pending, requires-external, signatures-pending, tests-started

#3 Not stored physics processes
  larg4/pluginActions/ParticleListAction_service.cxx
  larg4/pluginActions/ParticleListAction_service.h
Labels: L1-approved, L2-approved, code-checks-approved, fully-signed, tests-started

#5 declare project language and update cmake_minimum_required
  CMakeLists.txt
Labels: L1-approved, L2-approved, code-checks-approved, fully-signed, tests-started
